---
# tasks file for snow-acm
- name: Create change request
  servicenow.itsm.change_request:
    instance:
      host: "{{ snow_credentials.instance | default(snow_instance, true)}}" 
      username: "{{ snow_credentials.username | default(snow_username, true)}}"
      password: "{{ snow_credentials.password | default(snow_password, true)}}"

    type: standard
    state: new
    requested_by: admin
    short_description: Deploy application in an OpenShift Cluster 
    description: Using GitOps way, an application needs to be deployed in the target OpenShift Clusters.
    priority: moderate
    risk: low
    impact: low

    other:
      expected_start: 2022-05-24
